# umbrella/values.yaml

service-a:
  replicaCount: 2
  image:
    repository: nginx
    tag: "1.27"
  service:
    type: ClusterIP
    port: 80

service-b:
  replicaCount: 1
  image:
    repository: redis
    tag: "7.2"
  service:
    type: ClusterIP
    port: 6379
